[package]
name = "causality-tools"
version = "0.1.0"
edition = "2021"
description = "Causality Tools - CLI utilities for the Causality system"
license = "MIT OR Apache-2.0"

[dependencies]
# External dependencies
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
colored = "2.0"

# Internal dependencies
causality-types = { workspace = true }
causality-core = { workspace = true }
causality-engine = { workspace = true }
causality-domain = { workspace = true }

[dev-dependencies]
tempfile = "3.8"
