// Auto-generated test module imports
// Generated by move_tests_by_mapping.sh

pub mod account;
pub mod api;
pub mod archival;
pub mod capability;
pub mod effects;
pub mod epoch;
pub mod gc;
pub mod lifecycle;
pub mod register;
pub mod registry;
pub mod storage;
pub mod summarization;
pub mod templates;
pub mod versioning;
