[package]
name = "causality-types"
version = "0.1.0"
edition = "2021"
description = "Core types for the Causality framework"
authors = ["TimeWave Labs"]
rust-version = "1.70.0"
license = "Apache-2.0"

[lib]

[features]
default = ["std", "getrandom", "serde", "ssz", "sexpr"]
std = []
getrandom = ["dep:getrandom"]
# Optional serde support for ZK crate compatibility
serde = ["dep:serde", "serde/derive", "dep:serde_json"]
ssz = []
sexpr = ["lexpr"]
benchmarks = ["dep:criterion"]

[dependencies]
# Error handling
anyhow = { workspace = true }
thiserror = "1.0.50"

# Cryptography
sha2 = "0.10.8"
hex = "0.4.3"
getrandom = { version = "0.2.10", optional = true }

# Optional serialization support for ZK compatibility only
serde = { version = "1.0", optional = true, features = ["derive"] }
serde_json = { version = "1.0", optional = true }

# S-expression handling for Rust/OCaml interoperability
lexpr = { version = "0.2.7", optional = true }

# Required for traits with async methods
async-trait = "0.1.74"

# Required for HList types
frunk = "0.4.2"

# Required for logging
log = "0.4.20"

# Required for effects system
inventory = "0.3.12"

# Required for benchmarks
criterion = { version = "0.5.1", optional = true }

# Arbitrary precision arithmetic for ZK compatibility
dashu = { version = "0.4", default-features = false, features = ["std"] }
