[package]
name = "causality-types"
version = "0.1.0"
edition = "2021"
description = "Causality - Core type definitions"
license = "MIT OR Apache-2.0"

[dependencies]
# External dependencies
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
borsh = { workspace = true }
rand = { workspace = true }
chrono = { workspace = true }
hex = { workspace = true }
lazy_static = "1.4"
parking_lot = "0.12"

# This is a base crate with no internal dependencies
