[package]
name = "causality-types"
version = "0.1.0"
edition = "2021"
description = "Causality - Core types and definitions"
license = "MIT OR Apache-2.0"

[dependencies]
# External dependencies using workspace definitions
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
borsh = { workspace = true }
chrono = { workspace = true }
hex = { workspace = true }
rand = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
sha2 = { workspace = true }

# Specific external dependencies (not in workspace or different versions/features)
serde_bytes = "0.11"
blake3 = "1.5"
lazy_static = "1.4"

# Internal dependencies (if any)
# causality-error = { workspace = true } # Example if needed

[features]
default = []
