[package]
name = "causality-storage"
version = "0.1.0"
edition = "2021"
description = "Causality - Storage abstractions"
license = "MIT OR Apache-2.0"

[features]
default = []
memory = ["causality-db/memory"]
rocks = ["causality-db/rocks"]
all-db = ["memory", "rocks"]

[dependencies]
# External dependencies
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
borsh = { workspace = true }

# Internal dependencies
causality-types = { workspace = true }
causality-core = { workspace = true }

# Database dependency
causality-db = { workspace = true }
