[package]
name = "adapter-generator"
version = "0.1.0"
edition = "2021"
description = "A utility for generating effect adapters from schema definitions"

[dependencies]
tokio = { version = "1.28", features = ["macros", "rt-multi-thread", "fs"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
structopt = "0.3"
thiserror = "1.0"
colored = "2.0"
fs_extra = "1.2"
heck = "0.3"
handlebars = "4.3"
anyhow = "1.0"
chrono = "0.4"
blake3 = "1.5"
bincode = "1.3"
uuid = { version = "1.6", features = ["v4"] }
rand = "0.8"
base64 = { version = "0.21", optional = true }
hex = "0.4"
tempfile = "3.3"
actix-web = "4.4"
lazy_static = "1.4"
async-trait = "0.1"
sha2 = "0.10"
md5 = { version = "0.7.0", optional = true }
cosmwasm-std = { version = "1.2.0", optional = true }

[lib]
proc-macro = false

[features]
default = ["std"]
std = []
cosmwasm_zk = ["zk-proving", "cosmwasm-std", "md5", "base64"]
code-repo = []
domain = []
content-addressing = []
full-effect = []
boundary = []
on_chain = ["boundary"]
off_chain = ["boundary"]
zk-vm = []
zk-proving = []

[[bin]]
name = "adapter-gen"
path = "src/main.rs"

[[bin]]
name = "zk_demo"
path = "scripts/zk_demo.rs"

[[bin]]
name = "succinct_demo"
path = "scripts/succinct_demo.rs"

# Examples for demonstrating program account UI models
[[example]]
name = "program_account_serialization"
path = "examples/program_account_serialization.rs"

[[example]]
name = "program_account_api"
path = "examples/program_account_api.rs"

[[example]]
name = "resource_capability"
path = "examples/resource_capability.rs"

[[example]]
name = "program_account_effect"
path = "examples/program_account_effect.rs"

[[example]]
name = "privacy_preserving_effect"
path = "examples/privacy_preserving_effect.rs"

[[example]]
name = "boundary_crossing"
path = "examples/boundary_crossing.rs"

[[example]]
name = "cosmwasm_zk_adapter"
path = "examples/cosmwasm_zk_adapter.rs"
required-features = ["cosmwasm_zk"] 