[package]
name = "adapter-generator"
version = "0.1.0"
edition = "2021"
description = "A utility for generating effect adapters from schema definitions"

[dependencies]
tokio = { version = "1.28.0", features = ["full"] }
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
structopt = "0.3"
thiserror = "1.0.40"
colored = "2.0"
fs_extra = "1.2"
heck = "0.3"
handlebars = "4.3"
anyhow = "1.0"
chrono = { version = "0.4.24", features = ["serde"] }
blake3 = "1.5"
bincode = "1.3"
uuid = { version = "1.3.3", features = ["v4", "serde"] }
rand = "0.8"
getrandom = "0.2"
base64 = { version = "0.21", optional = true }
hex = "0.4.3"
tempfile = "3.3"
actix-web = "4.4"
lazy_static = "1.4"
async-trait = "0.1.68"
md5 = { version = "0.7.0", optional = true }
cosmwasm-std = { version = "1.2.0", optional = true }
reqwest = { version = "0.11", features = ["json"] }
rocksdb = { version = "0.21.0", optional = true }
sparse-merkle-tree = "0.6.1"

[lib]
proc-macro = false

[features]
default = ["std", "base64", "md5"]
std = []
examples = []
cosmwasm_zk = ["zk-proving", "cosmwasm-std", "md5", "base64"]
code-repo = []
domain = []
content-addressing = []
full-effect = []
boundary = []
on_chain = ["boundary"]
off_chain = ["boundary"]
zk-vm = []
zk-proving = []
rocksdb = ["dep:rocksdb"]
# Signature schemes
ed25519 = []
ecdsa = []
bls = []
# ZK proof systems
groth16 = []
plonk = []
# Hash functions
poseidon = []

[[bin]]
name = "adapter-gen"
path = "src/main.rs"

[[bin]]
name = "zk_demo"
path = "scripts/zk_demo.rs"

[[bin]]
name = "succinct_demo"
path = "scripts/succinct_demo.rs"

# Examples for demonstrating program account UI models
[[example]]
name = "program_account_serialization"
path = "examples/program_account_serialization.rs"

[[example]]
name = "program_account_api"
path = "examples/program_account_api.rs"

[[example]]
name = "resource_capability"
path = "examples/resource_capability.rs"

[[example]]
name = "program_account_effect"
path = "examples/program_account_effect.rs"

[[example]]
name = "boundary_crossing"
path = "examples/boundary_crossing.rs"

[[example]]
name = "cosmwasm_zk_adapter"
path = "examples/cosmwasm_zk_adapter.rs"
required-features = ["cosmwasm_zk"]

[[example]]
name = "cross_domain_relationships"
path = "src/examples/cross_domain_relationships.rs"
required-features = ["examples"] 
