[package]
name = "causality-runtime"
version = "0.1.0"
edition = "2021"
authors = ["Timewave Labs"]
description = "Runtime system for executing Causality effects with interpreter/handler separation"
license = "Apache-2.0"
repository = "https://github.com/timewave-computer/reverse-causality"

[dependencies]
# Core causality dependencies
causality-core = { path = "../causality-core" }
# causality-zk = { path = "../causality-zk" }  # Temporarily disabled due to API compatibility issues

# Error handling
thiserror = { workspace = true }
anyhow = { workspace = true }

# Serialization
serde = { workspace = true }
serde_json = { workspace = true }
ethereum_ssz = { workspace = true }

# Logging
log = { workspace = true }

# System info
num_cpus = "1.16"

# Async runtime (optional)
tokio = { workspace = true, optional = true }

[features]
default = []
async = ["tokio"]

[dev-dependencies]
env_logger = "0.10" 