[package]
name = "causality-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
causality-types = { path = "../causality-types" }
causality-lisp = { path = "../causality-lisp" }
causality-api = { path = "../causality-api" }
causality-runtime = { path = "../causality-runtime" }
anyhow = "1.0"
clap = { version = "4.3", features = ["derive"] }
# Use SSZ serialization instead of ssz
ethereum_ssz = { workspace = true }
ethereum_ssz_derive = { workspace = true }
async-trait = { workspace = true }
indicatif = "0.16.2"
tokio = { version = "1.0", features = ["full", "macros"] }
chrono = "0.4"
colored = "2.1.0"
hex = "0.4"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = { workspace = true }
url = "2.4.1"

[[bin]]
name = "causality"
path = "src/main.rs"
