[package]
name = "causality-core"
version = "0.1.0"
description = "Core components for Causality"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
# Asynchronous runtime
tokio = { version = "1.32", features = ["full"] }
async-trait = "0.1"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
borsh = "0.10"
toml = "0.7"
bincode = "1.3"

# Error handling
thiserror = "1.0"
anyhow = "1.0"

# Utilities
once_cell = "1.18"
chrono = { version = "0.4", features = ["serde"] }
itertools = "0.11"
futures = "0.3"
bytes = "1.4"
log = "0.4"
rand = "0.8"
blake3 = "1.0"
regex = "1.5"
jsonschema = "0.16"
uuid = { version = "1.3", features = ["v4", "serde"] }
jsonpath_lib = "0.3"

# HTTP client
reqwest = { version = "0.11", features = ["json"] }

# Cryptography
causality-crypto = { path = "../causality-crypto" }
sha2 = "0.10"
hex = "0.4"

# Types
causality-types = { path = "../causality-types" }

# Optional ZK integration (commented out until the package is available)
# zk-framework = { version = "0.1", optional = true }

[features]
default = []
# zk = ["zk-framework"]
zk = [] # Temporarily disabled until zk-framework is available
resource = [] # Enable resource management functionality
