[package]
name = "causality-core"
version = "0.1.0"
description = "Core components for Causality"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
# Asynchronous runtime
tokio = { version = "1.32", features = ["full"] }
async-trait = "0.1"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
borsh = "0.10"

# Error handling
thiserror = "1.0"
anyhow = "1.0"

# Utilities
once_cell = "1.18"
chrono = { version = "0.4", features = ["serde"] }
itertools = "0.11"
futures = "0.3"
bytes = "1.4"
log = "0.4"

# Cryptography
causality-crypto = { path = "../causality-crypto" }
sha2 = "0.10"
hex = "0.4"

# Optional ZK integration (commented out until the package is available)
# zk-framework = { version = "0.1", optional = true }

[features]
default = []
# zk = ["zk-framework"]
zk = [] # Temporarily disabled until zk-framework is available
resource = [] # Enable resource management functionality
