[package]
name = "causality-simulation"
version = "0.1.0"
edition = "2021"
authors = ["Causality Team"]
description = "Simulation and testing framework for Causality protocols"
license = "MIT OR Apache-2.0"
repository = "https://github.com/timewave/reverse-causality"

[dependencies]
anyhow = "1.0"
bincode = "1.3"
causality-core = { path = "../causality-core" }
causality-lisp = { path = "../causality-lisp" }
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.0", features = ["full"] }
uuid = { version = "1.0", features = ["v4"] }

[dev-dependencies]
tempfile = "3.8"
tokio-test = { workspace = true }
rand = { workspace = true }


