# Comprehensive CLI End-to-End Test Runner
[package]
name = "causality-cli-e2e"
version = "0.1.0"
edition = "2021"
authors = ["Causality Team"]
description = "End-to-end testing suite for the Causality CLI"

[dependencies]
# Core testing framework
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"

# CLI testing utilities
assert_cmd = "2.0"
predicates = "3.0"
assert_fs = "1.0"
tempfile = "3.0"

# Process and system interaction
which = "6.0"
regex = "1.0"

# Parallel test execution
rayon = "1.0"

# Logging and reporting
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Filesystem operations
walkdir = "2.0"
glob = "0.3"

# Time and duration
chrono = { version = "0.4", features = ["serde"] }

# Configuration and environment
dirs = "5.0"
home = "0.5"

# Causality crates for integration
causality-core = { path = "../../crates/causality-core" }

[dev-dependencies]
pretty_assertions = "1.4"

[features]
default = []
# Run tests that require network access
network = []
# Run tests against live testnets 
testnet = []
# Extended test suite with longer-running tests
extended = [] 