[package]
name = "causality-zk"
version = "0.1.0"
edition = "2021"
authors = ["Causality Team"]
description = "Zero-knowledge proof infrastructure for the Causality system"
license = "MIT"

[dependencies]
causality-core = { version = "0.1.0", path = "../causality-core" }

# Traverse storage proof integration (optional)
traverse-core = { git = "https://github.com/timewave-computer/traverse", default-features = false, optional = true }
traverse-ethereum = { git = "https://github.com/timewave-computer/traverse", optional = true }
traverse-valence = { git = "https://github.com/timewave-computer/traverse", features = ["alloc"], optional = true }

# Valence coprocessor integration (optional)
valence-coprocessor = { git = "https://github.com/timewave-computer/valence-coprocessor.git", tag = "v0.1.13", default-features = false, optional = true }
valence-coprocessor-client = { git = "https://github.com/timewave-computer/valence-domain-clients", rev = "d26460ceb0f95599300b1521131ef4b078638310", optional = true }

# Core utilities
anyhow = "1.0"
thiserror = "1.0"
serde = { workspace = true }
serde_json = "1.0"
sha2 = "0.10"
rand = "0.8"
bincode = "1.3"
hex = "0.4"
chrono = { version = "0.4", features = ["serde"] }
async-trait = "0.1"
base64 = "0.21"
log = "0.4"
tokio = { version = "1.0", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
uuid = { version = "1.0", features = ["v4"] }
url = "2.5"

# ZK backend integrations (optional)
sp1-sdk = { version = "1.0", optional = true }
risc0-zkvm = { version = "0.19", optional = true }

[features]
default = ["mock"]
mock = []  # Mock backend for testing
sp1 = ["dep:sp1-sdk"]
risc0 = ["dep:risc0-zkvm"]
traverse = ["dep:traverse-core", "dep:traverse-ethereum", "dep:traverse-valence"]
coprocessor = ["dep:valence-coprocessor", "dep:valence-coprocessor-client"]

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }

[[example]]
name = "zk_effect_demo"
path = "../../examples/zk_effect_demo.rs" 