[package]
name = "causality-toolkit"
version = "0.1.0"
edition = "2021"

[features]
# Enable schema by default and have a testing feature
default = ["schema"]
schema = []
testing = ["tempfile", "tracing", "tracing-subscriber"]

[dependencies]
causality-types = { path = "../causality-types", features = ["std"] }
causality-lisp = { path = "../causality-lisp" }
causality-runtime = { path = "../causality-runtime" }
causality-compiler = { path = "../causality-compiler" }
causality-core = { path = "../causality-core" }
sha2 = "0.10"

# Use workspace dependencies consistently
ethereum_ssz = { workspace = true }
ethereum_ssz_derive = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
once_cell = "1.19"
derive_more = "0.99"
uuid = { version = "1.6", features = ["v4"] }
chrono = { workspace = true }
thiserror = { workspace = true }
hex = { workspace = true }
log = { workspace = true }
tokio = { workspace = true }

# Testing dependencies (optional)
tempfile = { workspace = true, optional = true }
tracing = { version = "0.1", optional = true }
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt", "json"], optional = true }

[dev-dependencies] 
tokio-test = "0.4"
