[package]
name = "causality-tel"
version = "0.1.0"
edition = "2021"
description = "Causality - Transaction Execution Layer"
license = "MIT OR Apache-2.0"

[dependencies]
# External dependencies
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
anyhow = { workspace = true }
tracing = { workspace = true }
async-trait = "0.1"
borsh = { workspace = true }
chumsky = "1.0.0-alpha.8"
futures = "0.3"
uuid = { version = "1", features = ["v4"] }
nom = "7.1.3"
log = "0.4"
tokio = { version = "1.0", features = ["full"] }
dashmap = "5.4"
lru = "0.12"
csv = "1.2"
regex = "1.10"
num_cpus = "1.16"
clap = { version = "4.4", features = ["derive"] }
colored = "2.0"
structopt = "0.3"
hex = "0.4"

# Internal dependencies
causality-types = { workspace = true }
causality-core = { workspace = true }
causality-ir = { workspace = true }
# causality-engine = { workspace = true } # Removed to break dependency cycle
causality-error = { workspace = true }
base64.workspace = true
chrono = { workspace = true, features = ["serde"] }
sha2.workspace = true
pin-utils = "0.1.0"

# DEPRECATED: Dependencies on legacy crates have been removed
# All functionality is now available through causality-core
# causality-resource = { workspace = true }
# causality-effects = { workspace = true }

[dev-dependencies]
# Add dev dependencies here
tempfile = "3.8.0"
