[package]
name = "causality-domain-cosmwasm"
version = "0.1.0"
edition = "2021"
description = "Causality - cosmwasm domain adapter"
license = "MIT OR Apache-2.0"

[dependencies]
# External dependencies
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }

# Internal dependencies - now uncommented
causality-types = { workspace = true }
causality-core = { workspace = true }
causality-domain = { workspace = true }

# DEPRECATED: Dependencies on legacy crates have been removed
# All functionality is now available through causality-core
# causality-resource = { workspace = true }
