[package]
name = "causality-resource"
version = "0.1.0"
edition = "2021"
description = "Causality - Resource management system"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["interface", "adapter"]
# Core resource interfaces
interface = []
# Adapter patterns for cross-system integration
adapter = ["interface"]
# Domain-specific resource functionality
domain-resource = ["interface", "adapter"]
# Effect-specific resource functionality
effect-resource = ["interface", "adapter"]
# Legacy implementations (deprecated)
legacy = []
# Full resource management system
full = ["interface", "adapter", "domain-resource", "effect-resource"]

# Deprecation control features
# Treat deprecations as errors (for CI and enforcing migration)
deprecation-error = []
# Allow deprecated features (for transition period)
allow-deprecated = []
# Suppress deprecation warnings
suppress-deprecation-warnings = []

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
futures = "0.3"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.0", features = ["rt", "sync", "time", "macros"] }

# Internal dependencies
causality-common = { path = "../causality-common" }
causality-types = { path = "../causality-types" }
causality-crypto = { path = "../causality-crypto" }

# Optional dependencies for specific features
causality-domain = { path = "../causality-domain", optional = true }
causality-effects = { path = "../causality-effects", optional = true }
